spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/beautyhub_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Fr07051936#}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:mySecretKey}
jwt.issuer=${JWT_ISSUER:beautyhub}